### ISSUE TITLE
Onboard all new users to data.gov org and spaces for cloud.gov

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-cloud-migration#1]
This was moved from https://github.com/GSA/data.gov/issues/701

**Comment by hkdctol** [comment]
Is this task still incomplete?

**Comment by afeld** [comment]
FYI that this is now self-serve:

https://docs.cloud.gov/apps/managing-teammates/

**Comment by JJediny** [comment]
Application Team has been onboarded
