### ISSUE TITLE
Setup Docker-Bosh deployment for Data.gov

### ISSUE THREAD

**Issue by jdrowe** [GSA/datagov-cloud-migration#18]
Create Docker-Bosh deployment with Docker-Swarm, and deploy  ShipYard on that to manage Docker for Data.gov:

https://github.com/cloudfoundry-community/docker-boshrelease

http://shipyard-project.com/

- [x] Setup VPC with subnets, IGW, NAT Gateway Service
- [x] Setup Security Groups for instances to be assigned into
- [x] Create Bosh Director
- [x] Upload docker-boshrelase BOSH "Release"
- [x] Setup Docker Swarm Deployment https://github.com/cloudfoundry-community/docker-boshrelease/blob/master/examples/docker-swarm-aws.yml
- [x] Launch ShipYard onto Docker Swarm deployment
- [x] Launch sample application onto ShipYard to ensure the whole stack works as expected

**Comment by JJediny** [comment]
for reference.. shipyard on IRC channel:
http://webchat.freenode.net/?channels=%23shipyard&uio=d4

logs:
https://botbot.me/freenode/shipyard/

https://shipyard-project.com/deploy
