### ISSUE TITLE
Create manifest and deployment script for WordPress

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-cloud-migration#7]
The [current WordPress deployment process](https://github.com/GSA/datagov-deploy) needs to be ported to Cloud Foundry. We can start from [this example](https://github.com/18F/cf-ex-wordpress/) (specifically this [script](https://github.com/18F/cf-ex-wordpress/blob/master/.extensions/wordpress/extension.py)) but we'll want to take a different approach to handling persistence. We shouldn't need persistence for plugins or themes and we probably shouldn't use the SSH mounting approach at all, but we will want persistence for uploaded media. For this we should use S3 or something similar.

**Comment by afeld** [comment]
This many help:

https://github.com/18F/how-to-deploy/tree/master/wordpress

**Comment by philipashlock** [comment]
Thanks @afeld. That looks like it's just another pointer to the same script I'd already linked to, but if there's any more of a deployment guide, please let us know. 

A few notes on the existing extension.py script approach: 
* We should probably just use S3 for persistent storage which we may be able to do with the W3 Total Cache plugin which is already being used. Though I'm not sure if any S3 integration would actually happen through CF with that approach. 
* We shouldn't need to use the SSH mounted drive for plugins or themes. I think those can be just as ephemeral as the core wordpress app

**Comment by dano-reisys** [comment]
gsa/datagov-deploy#6

**Comment by dano-reisys** [comment]
https://github.com/GSA/datagov-deploy/issues/6
